<a href="https://colab.research.google.com/github/jrats/Assignment_EEGClassification/blob/main/tensors_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.11.0+cpu


In [3]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU.")

GPU not available. Using CPU.


# **Creating a Tensor**


In [4]:
#using empty
a=torch.empty(2,3)  #allocate memory

In [5]:
#check type
type(a)

torch.Tensor

In [6]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#using rand
torch.rand(2,3)

tensor([[0.6452, 0.3057, 0.7211],
        [0.2109, 0.6845, 0.2797]])

In [9]:
#use of seed using manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
#other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# linspace
print("using linspace ->", torch.linspace(0,10,8))

#using eye
print("using eye ->", torch.eye(5))

#using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.4286,  2.8571,  4.2857,  5.7143,  7.1429,  8.5714, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[         0,          0,          0],
        [        65,  980771632, 1064121552]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [25]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [19]:
# find data type
x.dtype

torch.int64

In [21]:
# assign data type
torch.tensor([1,2,3], dtype= torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1,2,3], dtype= torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Mathematical Operations

# 1. Scalar Operation

In [27]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [36]:
# math operations
# addition
x + 2
# substraction
x - 2
# multiplication
x * 2
# # division
x / 3
# int division
(x * 100)//3
# # mod
((x * 100)//3) % 2
# # power
x ** 2




tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

# 2. Element wise operations

In [41]:
a = torch.rand(2,3)
print(a)
b = torch.rand(2,3)
print(b)

tensor([[0.3182, 0.5261, 0.0447],
        [0.5123, 0.9051, 0.5989]])
tensor([[0.4450, 0.7278, 0.4563],
        [0.3389, 0.6211, 0.5530]])


In [44]:
# add
a + b

tensor([[0.7632, 1.2539, 0.5009],
        [0.8512, 1.5262, 1.1519]])

In [45]:
# sub
a - b

tensor([[-0.1268, -0.2017, -0.4116],
        [ 0.1735,  0.2839,  0.0458]])

In [46]:
# multiply
a * b

tensor([[0.1416, 0.3829, 0.0204],
        [0.1736, 0.5622, 0.3312]])

In [47]:
# division
a/b

tensor([[0.7151, 0.7228, 0.0979],
        [1.5119, 1.4571, 1.0829]])

In [48]:
# power
a**b

tensor([[0.6008, 0.6266, 0.2421],
        [0.7972, 0.9399, 0.7531]])

In [49]:
# mod
a % b

tensor([[0.3182, 0.5261, 0.0447],
        [0.1735, 0.2839, 0.0458]])

In [50]:
c = torch.tensor([-1, -2, -3, -4])

In [51]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [52]:
# negative
torch.negative(c)

tensor([1, 2, 3, 4])

In [53]:
# round
torch.round(c)

tensor([-1, -2, -3, -4])

In [54]:
# ceil
torch.ceil(c)

tensor([-1, -2, -3, -4])

In [55]:
# floor
torch.floor(c)

tensor([-1, -2, -3, -4])

In [64]:
# clamp
torch.clamp(c, min=-2, max=0)

tensor([-1, -2, -2, -2])

# 3. Reduction Operation

In [78]:
e = torch.randint(size=(2,3), low=0, high=100, dtype=torch.float32)
e

tensor([[63.,  5., 50.],
        [76., 94., 40.]])

In [79]:
# sum
torch.sum(e)

tensor(328.)

In [80]:
# sum along columns
torch.sum(e, dim=0)

tensor([139.,  99.,  90.])

In [81]:
# sum along rows
torch.sum(e, dim=1)

tensor([118., 210.])

In [82]:
# mean
torch.mean(e)

tensor(54.6667)

In [83]:
torch.mean(e, dim=1)

tensor([39.3333, 70.0000])

In [84]:
torch.median(e)

tensor(50.)

In [85]:
torch.max(e)

tensor(94.)

In [86]:
torch.min(e)

tensor(5.)

In [87]:
torch.prod(e)

tensor(4.5007e+09)

In [88]:
torch.var(e)

tensor(955.0667)

In [89]:
torch.argmax(e)

tensor(4)

In [90]:
torch.argmin(e)

tensor(1)

# 4. Matrix Operations

In [93]:
f = torch.randint(size=(2,3), low=0, high=30)
g = torch.randint(size=(3,2), low=0, high=20)
print(f)
print(g)

tensor([[ 7,  2, 15],
        [16, 21, 24]])
tensor([[15,  6],
        [19, 12],
        [ 3,  1]])


In [94]:
torch.matmul(f,g)

tensor([[188,  81],
        [711, 372]])

In [95]:
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

In [96]:
torch.dot(vec1, vec2)

tensor(11)

In [104]:
torch.transpose(f, 0, 1)

tensor([[ 7, 16],
        [ 2, 21],
        [15, 24]])

In [105]:
h = torch.randint(size=(3,3), low=0, high = 20, dtype= torch.float32)
h


tensor([[ 6., 18.,  4.],
        [19., 10., 17.],
        [19., 12., 17.]])

In [107]:
torch.det(h)

tensor(-52.0000)

In [108]:
torch.inverse(h)

tensor([[ 6.5385e-01,  4.9615e+00, -5.1154e+00],
        [ 7.8042e-10, -5.0000e-01,  5.0000e-01],
        [-7.3077e-01, -5.1923e+00,  5.4231e+00]])

# 5. Comparison Operations

In [112]:
j = torch.randint(size=(2,3), low=0, high=10)
k = torch.randint(size=(2,3), low=0, high=10)
print(j)
print(k)

tensor([[2, 2, 3],
        [7, 1, 5]])
tensor([[0, 2, 3],
        [7, 0, 2]])


In [113]:
# greater than
j > k

tensor([[ True, False, False],
        [False,  True,  True]])

In [114]:
j<k

tensor([[False, False, False],
        [False, False, False]])

In [115]:
j==k

tensor([[False,  True,  True],
        [ True, False, False]])

In [116]:
j != k

tensor([[ True, False, False],
        [False,  True,  True]])

In [117]:
j>=k

tensor([[True, True, True],
        [True, True, True]])

In [118]:
j<=k

tensor([[False,  True,  True],
        [ True, False, False]])

# 6. Special Functions

In [133]:
l = torch.randint(size=(2,3), low=0, high=100, dtype=torch.float32)
l

tensor([[ 3., 12., 27.],
        [29., 13., 59.]])

In [134]:
torch.log(l)

tensor([[1.0986, 2.4849, 3.2958],
        [3.3673, 2.5649, 4.0775]])

In [135]:
torch.exp(l)

tensor([[2.0086e+01, 1.6275e+05, 5.3205e+11],
        [3.9313e+12, 4.4241e+05, 4.2012e+25]])

In [136]:
torch.sqrt(l)

tensor([[1.7321, 3.4641, 5.1962],
        [5.3852, 3.6056, 7.6811]])

In [137]:
torch.sigmoid(l)

tensor([[0.9526, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])

In [138]:
torch.softmax(l, dim =0)

tensor([[5.1091e-12, 2.6894e-01, 1.2664e-14],
        [1.0000e+00, 7.3106e-01, 1.0000e+00]])

In [139]:
torch.relu(l)

tensor([[ 3., 12., 27.],
        [29., 13., 59.]])

# Inplace Operations

In [141]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.9792, 0.4947, 0.3617],
        [0.9687, 0.0359, 0.3041]])
tensor([[0.9867, 0.1290, 0.6887],
        [0.1637, 0.0899, 0.3139]])


In [142]:
m + n  #this will create a new tensor and not allocate space

tensor([[1.9659, 0.6237, 1.0504],
        [1.1323, 0.1258, 0.6180]])

In [145]:
m.add_(n)

tensor([[2.9525, 0.7527, 1.7390],
        [1.2960, 0.2158, 0.9319]])

In [146]:
m

tensor([[2.9525, 0.7527, 1.7390],
        [1.2960, 0.2158, 0.9319]])

In [147]:
n

tensor([[0.9867, 0.1290, 0.6887],
        [0.1637, 0.0899, 0.3139]])

In [148]:
torch.relu(m)  #not in place

tensor([[2.9525, 0.7527, 1.7390],
        [1.2960, 0.2158, 0.9319]])

In [149]:
m.relu_() #no value less than 0, hence we wont see a difference

tensor([[2.9525, 0.7527, 1.7390],
        [1.2960, 0.2158, 0.9319]])

# Copying a Tensor

In [160]:
a = torch.rand(2,3)
a

tensor([[0.2420, 0.4928, 0.5772],
        [0.3771, 0.2440, 0.8994]])

In [161]:
b = a #will result in changes in both

In [162]:
b

tensor([[0.2420, 0.4928, 0.5772],
        [0.3771, 0.2440, 0.8994]])

In [163]:
a[0][0] = 0

In [164]:
a

tensor([[0.0000, 0.4928, 0.5772],
        [0.3771, 0.2440, 0.8994]])

In [165]:
b #b will change as well

tensor([[0.0000, 0.4928, 0.5772],
        [0.3771, 0.2440, 0.8994]])

In [166]:
id(a)

135762846300224

In [167]:
id(b) #pointing to the same place as a

135762846300224

In [168]:
b = a.clone()

In [169]:
b

tensor([[0.0000, 0.4928, 0.5772],
        [0.3771, 0.2440, 0.8994]])

In [170]:
a[0][0] = 9

In [171]:
a

tensor([[9.0000, 0.4928, 0.5772],
        [0.3771, 0.2440, 0.8994]])

In [172]:
b #pointing to different place than a

tensor([[0.0000, 0.4928, 0.5772],
        [0.3771, 0.2440, 0.8994]])

# Tensor Operations on GPU

In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [5]:
device = torch.device('cuda')

In [6]:
# creating a new tensor on GPU(vRAM)
torch.rand((2,3), device = device)


tensor([[0.6718, 0.4843, 0.7379],
        [0.4062, 0.6075, 0.5323]], device='cuda:0')

In [8]:
a = torch.rand(2,3)

In [12]:
#moving an existing tensor to GPU
b=a.to(device)

In [13]:
b+5 #operations taking place on gpu

tensor([[5.4055, 5.7726, 5.3977],
        [5.6509, 5.2619, 5.9118]], device='cuda:0')

In [4]:
# comparing operations on the CPU and GPU

import torch
import time
size = 10000

# matrices on the CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

#Operations on the CPU
start_time= time.time()
result_cpu= torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# move matrices on the GPU
matrix_gpu1 = matrix_cpu1.to("cuda")
matrix_gpu2 = matrix_cpu2.to("cuda")


# Operations on the GPU

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

print("\n Speedup (CPU Time/ GPU Time):", cpu_time/ gpu_time)


Time on CPU: 17.4037 seconds
Time on GPU: 0.6769 seconds

 Speedup (CPU Time/ GPU Time): 25.712206902187543


# Reshaping Tensors

In [2]:
import torch

In [3]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [5]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
b = torch.rand(2,3,4)
b

tensor([[[0.3518, 0.9228, 0.1675, 0.0995],
         [0.2557, 0.4576, 0.7310, 0.2088],
         [0.4148, 0.7817, 0.0144, 0.1328]],

        [[0.7128, 0.9624, 0.4737, 0.7871],
         [0.2363, 0.0823, 0.8110, 0.5015],
         [0.8322, 0.2281, 0.9829, 0.0622]]])

In [7]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [10]:
#unsqueeze
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [12]:
# squeeze
d = torch.rand(1,20)
d

tensor([[0.0375, 0.6773, 0.5155, 0.9954, 0.1109, 0.1867, 0.6183, 0.5513, 0.0848,
         0.7285, 0.2768, 0.0467, 0.0503, 0.9403, 0.1170, 0.3194, 0.0011, 0.7622,
         0.8650, 0.2566]])

In [13]:
d.squeeze(0).shape

torch.Size([20])

# Numpy to PyTorch

In [14]:
import numpy as np

In [15]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [16]:
b = a.numpy()
b

array([1, 2, 3])

In [17]:
type(b)

numpy.ndarray

In [18]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [19]:
torch.from_numpy(c)


tensor([1, 2, 3])